name: PRO ESTATE
favicon: null
layout_spectrum: 0.75723
typography_spectrum: 0.80415
title: Your Real Estate. Our Business.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6330f'
    - '#ea6004'
    - '#f08800'
    - '#ffce00'
    - '#ff0000'
  brandStrength: 0.75
  lightness: 0.03868787712417543
  saturation: 1
  rhythmicContrast: 0.7626746450550854
purpose: []
